### ISSUE TITLE
automatically skip the component without styling file

### ISSUE THREAD

**Issue by maxisam** [ivanblazevic/ngx-unused-css#24]
```ts
@Component({
   templateUrl: './app.component.html',
   changeDetection: ChangeDetectionStrategy.OnPush
})
```
It will scan component like this and throws error.

Hope it can check component first and skip it.

or at least a way to exclude those html

**Comment by ivanblazevic** [comment]
@maxisam do you still have problems with the lib - fix was introduced month after your comment but I forgot to inform you?

**Comment by maxisam** [comment]
thanks for letting me know!
