### ISSUE TITLE
I don't understand how to run it.

### ISSUE THREAD

**Issue by gknbrdl** [ivanblazevic/ngx-unused-css#3]
I don't understand this step. 
https://github.com/ivanblazevic/ngx-unused-css#usage
![Screenshot_25](https://user-images.githubusercontent.com/5670040/62061321-94bafc00-b22f-11e9-9c58-f052e66e9656.jpg)

Can you be more descriptive. Thank you very much in advance.

**Comment by ivanblazevic** [comment]
I updated readme file, please check
