### ISSUE TITLE
Unknown problem after update.

### ISSUE THREAD

**Issue by SergKozyrev** [ivanblazevic/ngx-unused-css#32]
After update ngx-unused-css to 3.0.0 version, I have an error, can somebody help, please? 

![image](https://user-images.githubusercontent.com/40909123/119944416-ed2ec200-bf9c-11eb-9a1b-7c4c8e55b4c1.png)

**Comment by souber3746** [comment]
This issue is still persist. I'm using the latest version, v3.0.0
Please help me to overcome this.

![GitIssue](https://user-images.githubusercontent.com/8187909/141736388-7c5e5ddc-1ed2-4077-a4eb-6b6722c50323.png)

**Comment by ivanblazevic** [comment]
@souber3746 bugfix was released
