### ISSUE TITLE
Ignore list does not work

### ISSUE THREAD

**Issue by dolanmiu** [ivanblazevic/ngx-unused-css#5]
First of all,

Great plugin by the way, really appreciate this plugin! It has changed the way I code Angular, and is now part of the workflow / CI build process. Good work!

I found a problem with it though, the `ignore` config does not work properly

![Screenshot 2019-11-08 at 13 58 39](https://user-images.githubusercontent.com/2917613/68481783-fed03d80-022f-11ea-92fe-45c749d02f87.png)

**Comment by ivanblazevic** [comment]
Hi @dolanmiu, thnx for the nice words about the plugin. I apologise for such a long delay on replying here - but if you are still using the library and if you did not managed to solve the problem I just pushed simple example with full application structure so it is better to understand it:

Here you can see that I have sibling class with name `unused-to-ignore` similar to your case:
https://github.com/ivanblazevic/ngx-unused-css/blob/master/examples/simpleAngularApp/src/app/app.component.html#L329

In the config here you can see that I put that class to ignore 
https://github.com/ivanblazevic/ngx-unused-css/blob/master/examples/simpleAngularApp/.ngx-unused-css.json#L7

And if you run `npm run unusedCSS` you will see that ignored class is not reported.
Maybe you can try to update to latest version 2.0.0. which was fully refactored to TS and enriched with the unit tests. 

However, in case you still have the problem pls just share some example and I am happy to help - this time I will try to be quicker on the response. All the best!
